### ISSUE TITLE
Map change: remove the buffer overlap 

### ISSUE THREAD

**Issue by nellepierson** [dcfemtech/hackforgood-waba-map#117]
We're looking to prevent buffers from overlapping when they cross jurisdictional lines to avoid the intestinal look. 

Possible with modifying svg directly: Pull all paths into a single <svg path> instead of multiple nodes. A little tedious, might be slow.

**Comment by mdelcambre** [comment]
A simple (from a coding/technology side) solution is to limit the buffers to only be within the county borders. This would automatically prevent any overlap from showing.  
However, it may look a bit strange when the neighbor county is not loaded, but perhaps that is acceptable. Given that we have the county lines, it should be pretty to easy for a user to understand what is going on.  Maybe argue it is a feature as it only gives a county credit for their own coverage :wink: .

**Comment by alongthepike** [comment]
I like @mdelcambre's recommendation. This could be as simple as calling [turf.intersect](http://turfjs.org/docs/#intersect) passing it the buffer polygon and the county border polygon before saving the buffer.  

And yes, this is definitely of use when we are calculating % of the jurisdiction's land area that is within X distance of bike infrastructure.  Right now Arlington's "% of jurisdiction within 1 mile of bike infrastructure" is calculating as over 100% because the buffer polygon extends beyond the actual jurisdiction.

**Comment by alongthepike** [comment]
![proofofconcept](https://cloud.githubusercontent.com/assets/13531063/18215953/ebd028a0-7121-11e6-916f-93d80657f7ac.png)

Proof of concept looks very promising.

**Comment by nellepierson** [comment]
woah, DC boundary extends west of the potomac? #Themoreyouknow

[image: Inline image 1]


*Nelle Pierson *| *Deputy Director *
*Washington Area Bicyclist Association*
2599 Ontario Rd NW Washington DC, 20009
Desk: 202-518-0524 x 202
Cell: 848-863-9442

Your membership results in better bike rides. Click here
<http://www.waba.org/get-involved/become-a-member/>to join or renew your
WABA membership.

**Comment by alongthepike** [comment]
Yep. DC owns ALL of the water and everything in it - TR Island is DC, Memorial Circle is DC.

**Comment by alulsh** [comment]
This was done in https://github.com/dcfemtech/hackforgood-waba-map/pull/131! 🎉
