### ISSUE TITLE
Admin tool to generate buffers on demand

### ISSUE THREAD

**Issue by NealHumphrey** [dcfemtech/hackforgood-waba-map#65]
Add an admin function that can be called to generate buffers based on the currently loaded lanes, so that new buffers can be easily created when needed. 

Add a percent completed indicator for the user to see progress.

**Comment by alulsh** [comment]
> Add an admin function that can be called to generate buffers based on the currently loaded lanes

This is great - I'm assuming we'd use [turf-buffer](https://github.com/Turfjs/turf-buffer) for this and it would be added to either [the bin](https://docs.npmjs.com/files/package.json#bin) or as a [script](https://docs.npmjs.com/misc/scripts)? People could run this locally in their terminal with node.

If so, we should initialize a `package.json` for this project, even though the demo will still be client-side and not run on a server. I'd like to add a linter that can be run via `npm test` anyway and hook this up to Travis CI.

**Comment by NealHumphrey** [comment]
Yes on turf-buffer and a couple other turf functions. 

I'm not that advanced - I'm not familiar with how to set up the rest of that stuff you mention. I was thinking of just making a function called `updateBuffer(distance)` that we can call from an /admin.html page. No need to run in the terminal, can just do it in browser.

**Comment by tomBeach** [comment]
Just uploaded some filter functionality for selecting region (DC, MoCo, Alex...) and setting buffer size for selected regions.  (Changes on my forked version at https://github.com/tomBeach/hackforgood-waba-map.)  Region selection works well but no "reset/clear" option for buffers yet.  I'm hoping to post a viewable version to check online... maybe by noon? Will keep you posted!

**Comment by tomBeach** [comment]
Here's a link to a "working" version to check out (bugs in the buffers selection...!) but it shows a crude design and basic interactivity...  link on my portfolio site: https://tombeach.github.io/hackforgood-waba-map/

**Comment by NealHumphrey** [comment]
@tomBeach this looks good! I haven't checked out the code yet. I'll ping you before I do anything to make sure I'm building on your stuff (won't have a chance to do much until this weekend)

**Comment by alulsh** [comment]
As discussed in https://github.com/dcfemtech/hackforgood-waba-map/issues/65#issuecomment-236662899, I created an initial `package.json` in https://github.com/dcfemtech/hackforgood-waba-map/pull/70.

**Comment by NealHumphrey** [comment]
@alulsh sorry but I'm giving up on this for now. I struggled with the nvm-windows tool for a couple hours before falling back to a regular node install, and now I've spent several more hours fighting turf and geojson data structures. I had things working fine in the browser world when the code was using the Mapbox featureLayers to get the geoJSON into the needed format, but now when I try to call turf functions on the loaded json data it returns blank feature collections. This was happening in the starter branch you set up and I couldn't figure out how to fix it. 

If you're open to doing it browser side I can make that work - it's easier to see what's going on with the data in the Chrome console instead of command prompts. Otherwise I need to pass this on to someone who knows this stuff better than me.

**Comment by alulsh** [comment]
> If you're open to doing it browser side I can make that work

Unfortunately creating the buffers client side is not a great option:

* client side JavaScript can only output the GeoJSON to the browser console - not easy to save, requires copying and pasting from console into a new text file 
* due to https://github.com/dcfemtech/hackforgood-waba-map/issues/1#issuecomment-236896149, generating the buffers client-side can take over 5 minutes and can crash the browser (depending on your laptop stats).
* offering an "admin button" on the front end UI of the map then allows a user to create a self-Denial of Service scenario where they can crash their own browser

Creating the buffers locally using Node allows for the easy generation of all of the buffers to file/disk. It's also considerably quicker than client-side generation and won't allow a user to crash their own browser. While we could host the admin button on a separate admin page, this still has the core problem of difficult copying and pasting from the console into various files.

> Otherwise I need to pass this on to someone who knows this stuff better than me.

In https://github.com/dcfemtech/hackforgood-waba-map/pull/76 @alongthepike mentions that their script "currently supports only Montgomery County, but can be expanded using various strategies to the other jurisdictions". May be worth closing this PR and instead expanding on https://github.com/dcfemtech/hackforgood-waba-map/pull/76 as an admin script to create all the buffer files.

**Comment by alongthepike** [comment]
To be clear #76  has nothing to do with generating buffers (it is pulling live bikeway data from MoCo's ArcGIS server).

I DID commit some working code into turf-buffer-admin-function though.  Easily expandable to all of the jurisdictions, though it could use some TLC from someone with a better grasp of turf.js than I have.  It is really, really slow on my machine and sometimes dies with an out of memory exception.

**Comment by NealHumphrey** [comment]
Thanks Chris! I can probably clean up the turf part, I'll give it a shot.

**Comment by alongthepike** [comment]
I believe this is done!
